### PR TITLE
Install React Font Awesome and add icons

### PR DESCRIPTION
**Pull request by KaylaKremer**
For issue #22

### CODE REVIEW

**Comment by manjeetaR** [comment]
> For issue #22

Edit icon for update does not suit our case. Could you check on this.

**Comment by KaylaKremer** [comment]
@manjeetaR Sure thing!

**Comment by manjeetaR** [comment]
> @manjeetaR Sure thing!

And please pull master and resolve the conflicts. There were many PR merged recently. You might get lot of changes.

**Comment by KaylaKremer** [comment]
@manjeetaR , I think this PR is good for you to review again!

**Pull request merged**
